DROP INDEX IF EXISTS monitors_kind_idx;
ALTER TABLE monitors DROP COLUMN IF EXISTS tls_mode;
ALTER TABLE monitors DROP COLUMN IF EXISTS port;
ALTER TABLE monitors DROP COLUMN IF EXISTS host;
ALTER TABLE monitors DROP COLUMN IF EXISTS kind;
