{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "toggle-monitor.serviceAccountName" . }}
  labels: {{- include "toggle-monitor.labels" . | nindent 4 }}
{{- end }}
